version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package

      - run: mvn clean package # run the actual tests
      - run: mvn clean compile jib:build -Dimage=baitholder/demo:$CIRCLE_BUILD_NUM

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar